version: '3'

services:
    web:
        container_name: ginger-dj-test
        build:
            context: .
            dockerfile: ./dev-compose/Dockerfile
        command: /bin/sh -c "while sleep 1000; do :; done"
        ports:
            - 8000:8000
        environment:
            - env=prod
            - DB_NAME=django_2
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - ALLOWED_HOSTS=localhost
            - CSRF_TRUSTED_ORIGINS=http://localhost
        volumes:
            - ./:/app
            - ~/.gitconfig:/etc/gitconfig
            - ~/.ssh:/root/.ssh
    prometheus:
        image: prom/prometheus
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - 9090:9090
        depends_on:
            - web
