[tool.pylint.MESSAGE_CONTROL]
disable = """
    line-too-long,
    abstract-method,
    no-member,
    invalid-name
"""
enable = "useless-suppression"

[tool.pylint.REPORTS]
reports="no"

[tool.pylint.FORMAT]
max-line-length="88"

[tool.pylint.BASIC]
good-names = "_,i,e,setUp,tearDown,maxDiff"

[tool.black]
line-length = 150
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = []
known_third_party = ["ginger", "prometheus_client"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.5.0"
version_files = [
    "pyproject.toml:version",
]

[coverage-threshold]
line_coverage_min = 68
