# Generated by Ginger 5.3.4 on 2024-06-10 13:17

import ginger.db.models.deletion
from ginger.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(choices=[("compulsary", "Compulsary"), ("elective", "Elective")], default="compulsary", max_length=50)),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("roll_number", models.CharField(max_length=40)),
                ("on_scholarship", models.BooleanField(default=True)),
                ("father_name", models.CharField(max_length=100, null=True)),
                ("address", models.TextField(max_length=500)),
                ("data_of_birth", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course", models.ForeignKey(null=True, on_delete=ginger.db.models.deletion.SET_NULL, to="src.course")),
                ("student", models.ForeignKey(on_delete=ginger.db.models.deletion.DO_NOTHING, related_name="courses", to="src.student")),
            ],
            options={
                "db_table": "enrollment",
            },
        ),
    ]
